// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: allin/user/v1/settings.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Theme    string `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_allin_user_v1_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_allin_user_v1_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_allin_user_v1_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Settings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

var File_allin_user_v1_settings_proto protoreflect.FileDescriptor

var file_allin_user_v1_settings_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x3c, 0x0a,
	0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x74,
	0x65, 0x63, 0x68, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x67, 0x6f, 0x2f,
	0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_allin_user_v1_settings_proto_rawDescOnce sync.Once
	file_allin_user_v1_settings_proto_rawDescData = file_allin_user_v1_settings_proto_rawDesc
)

func file_allin_user_v1_settings_proto_rawDescGZIP() []byte {
	file_allin_user_v1_settings_proto_rawDescOnce.Do(func() {
		file_allin_user_v1_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_allin_user_v1_settings_proto_rawDescData)
	})
	return file_allin_user_v1_settings_proto_rawDescData
}

var file_allin_user_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_allin_user_v1_settings_proto_goTypes = []interface{}{
	(*Settings)(nil), // 0: allin.user.v1.Settings
}
var file_allin_user_v1_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_allin_user_v1_settings_proto_init() }
func file_allin_user_v1_settings_proto_init() {
	if File_allin_user_v1_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_allin_user_v1_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_allin_user_v1_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_allin_user_v1_settings_proto_goTypes,
		DependencyIndexes: file_allin_user_v1_settings_proto_depIdxs,
		MessageInfos:      file_allin_user_v1_settings_proto_msgTypes,
	}.Build()
	File_allin_user_v1_settings_proto = out.File
	file_allin_user_v1_settings_proto_rawDesc = nil
	file_allin_user_v1_settings_proto_goTypes = nil
	file_allin_user_v1_settings_proto_depIdxs = nil
}
