// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: allin/messaging/v1/sms.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SMS 短信模板类型
type SMSTemplateType int32

const (
	SMSTemplateType_SMS_TEMPLATE_TYPE_UNSPECIFIED SMSTemplateType = 0
	SMSTemplateType_SMS_TEMPLATE_TYPE_WELCOME     SMSTemplateType = 1
	SMSTemplateType_SMS_TEMPLATE_TYPE_VERIFY_CODE SMSTemplateType = 2
)

// Enum value maps for SMSTemplateType.
var (
	SMSTemplateType_name = map[int32]string{
		0: "SMS_TEMPLATE_TYPE_UNSPECIFIED",
		1: "SMS_TEMPLATE_TYPE_WELCOME",
		2: "SMS_TEMPLATE_TYPE_VERIFY_CODE",
	}
	SMSTemplateType_value = map[string]int32{
		"SMS_TEMPLATE_TYPE_UNSPECIFIED": 0,
		"SMS_TEMPLATE_TYPE_WELCOME":     1,
		"SMS_TEMPLATE_TYPE_VERIFY_CODE": 2,
	}
)

func (x SMSTemplateType) Enum() *SMSTemplateType {
	p := new(SMSTemplateType)
	*p = x
	return p
}

func (x SMSTemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SMSTemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_allin_messaging_v1_sms_proto_enumTypes[0].Descriptor()
}

func (SMSTemplateType) Type() protoreflect.EnumType {
	return &file_allin_messaging_v1_sms_proto_enumTypes[0]
}

func (x SMSTemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SMSTemplateType.Descriptor instead.
func (SMSTemplateType) EnumDescriptor() ([]byte, []int) {
	return file_allin_messaging_v1_sms_proto_rawDescGZIP(), []int{0}
}

var File_allin_messaging_v1_sms_proto protoreflect.FileDescriptor

var file_allin_messaging_v1_sms_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2a, 0x76, 0x0a, 0x0f, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x4d, 0x53, 0x5f, 0x54, 0x45, 0x4d,
	0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x4d, 0x53, 0x5f,
	0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x45,
	0x4c, 0x43, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x4d, 0x53, 0x5f, 0x54,
	0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x45, 0x52,
	0x49, 0x46, 0x59, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x02, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x74, 0x65,
	0x63, 0x68, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x61,
	0x6c, 0x6c, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_allin_messaging_v1_sms_proto_rawDescOnce sync.Once
	file_allin_messaging_v1_sms_proto_rawDescData = file_allin_messaging_v1_sms_proto_rawDesc
)

func file_allin_messaging_v1_sms_proto_rawDescGZIP() []byte {
	file_allin_messaging_v1_sms_proto_rawDescOnce.Do(func() {
		file_allin_messaging_v1_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_allin_messaging_v1_sms_proto_rawDescData)
	})
	return file_allin_messaging_v1_sms_proto_rawDescData
}

var file_allin_messaging_v1_sms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_allin_messaging_v1_sms_proto_goTypes = []interface{}{
	(SMSTemplateType)(0), // 0: allin.messaging.v1.SMSTemplateType
}
var file_allin_messaging_v1_sms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_allin_messaging_v1_sms_proto_init() }
func file_allin_messaging_v1_sms_proto_init() {
	if File_allin_messaging_v1_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_allin_messaging_v1_sms_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_allin_messaging_v1_sms_proto_goTypes,
		DependencyIndexes: file_allin_messaging_v1_sms_proto_depIdxs,
		EnumInfos:         file_allin_messaging_v1_sms_proto_enumTypes,
	}.Build()
	File_allin_messaging_v1_sms_proto = out.File
	file_allin_messaging_v1_sms_proto_rawDesc = nil
	file_allin_messaging_v1_sms_proto_goTypes = nil
	file_allin_messaging_v1_sms_proto_depIdxs = nil
}
