// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: common/enums.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 语言类型枚举
type Language int32

const (
	Language_ZH_CN Language = 0  // 中文（简体）
	Language_ZH_TW Language = 1  // 中文（繁体）
	Language_EN_US Language = 2  // 英文（美国）
	Language_EN_GB Language = 3  // 英文（英国）
	Language_JA_JP Language = 4  // 日文
	Language_KO_KR Language = 5  // 韩文
	Language_FR_FR Language = 6  // 法文
	Language_DE_DE Language = 7  // 德文
	Language_ES_ES Language = 8  // 西班牙文
	Language_IT_IT Language = 9  // 意大利文
	Language_RU_RU Language = 10 // 俄文
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0:  "ZH_CN",
		1:  "ZH_TW",
		2:  "EN_US",
		3:  "EN_GB",
		4:  "JA_JP",
		5:  "KO_KR",
		6:  "FR_FR",
		7:  "DE_DE",
		8:  "ES_ES",
		9:  "IT_IT",
		10: "RU_RU",
	}
	Language_value = map[string]int32{
		"ZH_CN": 0,
		"ZH_TW": 1,
		"EN_US": 2,
		"EN_GB": 3,
		"JA_JP": 4,
		"KO_KR": 5,
		"FR_FR": 6,
		"DE_DE": 7,
		"ES_ES": 8,
		"IT_IT": 9,
		"RU_RU": 10,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enums_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_common_enums_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_common_enums_proto_rawDescGZIP(), []int{0}
}

var File_common_enums_proto protoreflect.FileDescriptor

var file_common_enums_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x83, 0x01, 0x0a,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x5a, 0x48, 0x5f,
	0x43, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x5a, 0x48, 0x5f, 0x54, 0x57, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x4e, 0x5f, 0x55, 0x53, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e,
	0x5f, 0x47, 0x42, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x41, 0x5f, 0x4a, 0x50, 0x10, 0x04,
	0x12, 0x09, 0x0a, 0x05, 0x4b, 0x4f, 0x5f, 0x4b, 0x52, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x46,
	0x52, 0x5f, 0x46, 0x52, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x5f, 0x44, 0x45, 0x10,
	0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x53, 0x5f, 0x45, 0x53, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x54, 0x5f, 0x49, 0x54, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x55, 0x5f, 0x52, 0x55,
	0x10, 0x0a, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x6c, 0x6c, 0x69, 0x6e, 0x74, 0x65, 0x63, 0x68, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_enums_proto_rawDescOnce sync.Once
	file_common_enums_proto_rawDescData = file_common_enums_proto_rawDesc
)

func file_common_enums_proto_rawDescGZIP() []byte {
	file_common_enums_proto_rawDescOnce.Do(func() {
		file_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_enums_proto_rawDescData)
	})
	return file_common_enums_proto_rawDescData
}

var file_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_enums_proto_goTypes = []interface{}{
	(Language)(0), // 0: common.Language
}
var file_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_enums_proto_init() }
func file_common_enums_proto_init() {
	if File_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_enums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_enums_proto_goTypes,
		DependencyIndexes: file_common_enums_proto_depIdxs,
		EnumInfos:         file_common_enums_proto_enumTypes,
	}.Build()
	File_common_enums_proto = out.File
	file_common_enums_proto_rawDesc = nil
	file_common_enums_proto_goTypes = nil
	file_common_enums_proto_depIdxs = nil
}
